using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using POS.EPL;

namespace POS.PL
{
    public partial class FrmCustomers : Form
    {
        DB_SMP db_smp =new DB_SMP();
        TB_Cus tb_cus = new TB_Cus();
        BL.LibraryProject lp = new BL.LibraryProject();
        EPL.FrmDialog dlg = new EPL.FrmDialog();
        EPL.FrmToast  toast =  new  FrmToast();
        public int id;
        public FrmCustomers()
        {
            InitializeComponent();

         
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            POS.DB_SMP dbContext = new POS.DB_SMP();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Cus.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControltable.DataSource = dbContext.TB_Cus.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnInsert_Click(object sender, EventArgs e)
        {
            PL.FrmCustomersAdd frmcustomersadd= new FrmCustomersAdd();
            frmcustomersadd.ID = 0;
            frmcustomersadd.btn_insert.Text = "ADD";
            frmcustomersadd.Show();
        }

        private void btnUpdata_Click(object sender, EventArgs e)
        {
            PL.FrmCustomersAdd frmcustomersadd = new FrmCustomersAdd();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID_Cus"));
            tb_cus = db_smp.TB_Cus.Where(x => x.ID_Cus == id).FirstOrDefault();
            frmcustomersadd.txtname.Text = tb_cus.Name_Cus.ToString();
            frmcustomersadd.txtphone.Text = tb_cus.Phone_Cus.ToString();
            frmcustomersadd.txtemail.Text = tb_cus.Email_Cus.ToString();

            lp.by = tb_cus.img_Cus;
            frmcustomersadd.imageuser.Image = Image.FromStream(lp.convetImg());
            frmcustomersadd.ID = id;
            frmcustomersadd.btn_insert.Text = "UPDATA";
            frmcustomersadd.Show();
        }

        private void btndelete_Click(object sender, EventArgs e)
        {
            EPL.FrmToast frmToast = new FrmToast();
            EPL.FrmDialog frmdialog = new FrmDialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID_Cus"));
                DialogResult result = MessageBox.Show("Are Sure Of The Deleting Process", "Deletion process", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation);
                if (result == DialogResult.Yes)
                {
                    tb_cus = db_smp.TB_Cus.Where(x => x.ID_Cus == id).FirstOrDefault();
                    db_smp.Entry(tb_cus).State = EntityState.Deleted;
                    db_smp.SaveChanges();
                    toast.txtCaption.Text = "has been deleted Customer ";
                    toast.Show();
                    UpdateData();
                }
            }
            catch 
            {
                frmdialog.txtCaption.Text = "There Is No Customer To Delete";
                frmdialog.Width = this.Width;
                frmdialog.Show();
            }
        }

        private void btnreload_Click(object sender, EventArgs e)
        {
            UpdateData();
        }
        public void UpdateData()
        {
            db_smp = new DB_SMP();
            gridControltable.DataSource = db_smp.TB_Cus.ToList();
        }

        private void btnsearch_Click(object sender, EventArgs e)
        {
            var _search = txtsearch.Text;

            gridControltable.DataSource = db_smp.TB_Cus.Where(x => x.Name_Cus.Contains(_search)|| x.Phone_Cus.Contains(_search)).ToList();
        }
    }
}
