using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using POS.EPL;

namespace POS.PL
{
    public partial class FrmSupp: Form
    {
        DB_SMP db_smp =new DB_SMP();
        TB_supp tBsupp = new TB_supp();
        BL.LibraryProject lp = new BL.LibraryProject();
        EPL.FrmDialog dlg = new EPL.FrmDialog();
        EPL.FrmToast  toast =  new  FrmToast();
        public int id;
        public FrmSupp()
        {
            InitializeComponent();
          
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            POS.DB_SMP dbContext = new POS.DB_SMP();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_supp.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControltable.DataSource = dbContext.TB_supp.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnInsert_Click(object sender, EventArgs e)
        {
            PL.FrmSuppAdd suppadd = new FrmSuppAdd();
            suppadd.ID = 0;
            suppadd.btn_insert.Text = "ADD";
            suppadd.Show();
        }

        private void btnUpdata_Click(object sender, EventArgs e)
        {
            PL.FrmSuppAdd frmsuppadd = new FrmSuppAdd();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            tBsupp = db_smp.TB_supp.Where(x => x.ID_supp == id).FirstOrDefault();
            frmsuppadd.txtname.Text = tBsupp.Name_supp.ToString();
            frmsuppadd.txtphone.Text = tBsupp.Phone_supp.ToString();
            frmsuppadd.txtemail.Text = tBsupp.Email_supp.ToString();

            lp.by = tBsupp.img_supp;
            frmsuppadd.imageuser.Image = Image.FromStream(lp.convetImg());
            frmsuppadd.ID = id;
            frmsuppadd.btn_insert.Text = "UPDATA";
            frmsuppadd.Show();
        }

        private void btndelete_Click(object sender, EventArgs e)
        {
            EPL.FrmToast frmToast = new FrmToast();
            EPL.FrmDialog frmdialog = new FrmDialog();
            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID_supp"));
                DialogResult result = MessageBox.Show("Are Sure Of The Deleting Process", "Deletion process", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation);
                if (result == DialogResult.Yes)
                {
                    tBsupp = db_smp.TB_supp.Where(x => x.ID_supp == id).FirstOrDefault();
                    db_smp.Entry(tBsupp).State = EntityState.Deleted;
                    db_smp.SaveChanges();
                    toast.txtCaption.Text = "has been deleted supplier ";
                    toast.Show();
                    UpdateData();
                }
            }
            catch 
            {
                frmdialog.txtCaption.Text = "There Is No supplier To Delete";
                frmdialog.Width = this.Width;
                frmdialog.Show();
            }
        }

        private void btnreload_Click(object sender, EventArgs e)
        {
            UpdateData();
        }
        public void UpdateData()
        {
            db_smp = new DB_SMP();
            gridControltable.DataSource = db_smp.TB_supp.ToList();
        }

        private void btnsearch_Click(object sender, EventArgs e)
        {
            var _search = txtsearch.Text;

            gridControltable.DataSource = db_smp.TB_supp.Where(x => x.Name_supp.Contains(_search)|| x.Phone_supp.Contains(_search)).ToList();
        }
    }
}
