//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SMP : DbContext
    {
        public DB_SMP()
            : base("name=DB_SMP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_catogary> TB_catogary { get; set; }
        public virtual DbSet<TB_Pur> TB_Pur { get; set; }
        public virtual DbSet<TB_supp> TB_supp { get; set; }
        public virtual DbSet<TB_Cus> TB_Cus { get; set; }
        public virtual DbSet<TB_Sales> TB_Sales { get; set; }
        public virtual DbSet<TB_User> TB_User { get; set; }
        public virtual DbSet<TB_SystemLogs> TB_SystemLogs { get; set; }
        public virtual DbSet<TB_ABC> TB_ABC { get; set; }
    }
}
