//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cus
    {
        public int ID_Cus { get; set; }
        public string Name_Cus { get; set; }
        public string Phone_Cus { get; set; }
        public string Email_Cus { get; set; }
        public string Sex_Cus { get; set; }
        public byte[] img_Cus { get; set; }
    }
}
