//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pur
    {
        public int ID { get; set; }
        public Nullable<int> cat_ID { get; set; }
        public Nullable<int> ID_supp { get; set; }
        public string pur_Name { get; set; }
        public string Pur_type { get; set; }
        public string Pur_Cat { get; set; }
        public string Pur_Supp { get; set; }
        public string Pur_Det { get; set; }
        public Nullable<double> Pur_Buy { get; set; }
        public Nullable<double> Pur__sell { get; set; }
        public Nullable<double> Pur_Qt { get; set; }
        public Nullable<double> Pur_Tsell { get; set; }
        public Nullable<double> Pur_Tbuy { get; set; }
        public Nullable<double> Pur_TRev { get; set; }
    
        public virtual TB_catogary TB_catogary { get; set; }
        public virtual TB_supp TB_supp { get; set; }
    }
}
